notification_system/main/urls.py
from django.conf.urls import patterns, url, include
from rest_framework.routers import DefaultRouter

from main import views

router = DefaultRouter()
router.register(r'snippets', views.SnippetView)

urlpatterns = patterns('',
    url(r'^', include(router.urls)),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^runsql/$', views.runsql, name='runsql')
)

notification_system/notification_system/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from main import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^main/', include('main.urls')),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^openid/(.*)', SessionConsumer()),
)

notification_system/main/models.py
from django.db import models
from django.contrib.auth.models import User
from validators import validate_min_length


# Create your models here.
class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # Override the __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.user.username


class Profile(models.Model):
    user = models.ForeignKey(User)
    oauth_token = models.CharField(max_length=200)
    oauth_secret = models.CharField(max_length=200)

    def __unicode__(self):
        return unicode(self.user)


class Notification(models.Model):
    notify_by = models.ForeignKey(User, related_name="notify_by")
    header = models.CharField(max_length=150, validators=[validate_min_length])
    content = models.CharField(max_length=300, validators=[validate_min_length])
    image_url = models.URLField()
    notify_date = models.DateTimeField()
    notify_to = models.ManyToManyField(User, related_name="notify_to")
    sent = models.BooleanField(default=False)

    def __unicode__(self):
        return unicode(self.header)


class Snippet(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=100, blank=True, default='')
    code = models.TextField()
    linenos = models.BooleanField(default=False)

    class Meta:
        ordering = ('created',)

notification_system/main/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from main.models import UserProfile, Notification
from validators import validate_min_length


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class NotificationForm(forms.ModelForm):
    notify_to = forms.CharField(required=True)
    header = forms.CharField(required=True, validators=[validate_min_length])
    content = forms.CharField(
        required=False,
        widget=forms.Textarea,
        validators=[validate_min_length]
    )
    image_url = forms.URLField(required=False)
    notify_date = forms.DateTimeField(
        required=True,
        widget=forms.DateTimeInput(),
        input_formats=['%d/%m/%Y %H:%M'],
        help_text="Please enter date time in this format: dd/mm/yyyy hh:mm"
    )

    class Meta:
        model = Notification
        fields = ('header', 'content', 'image_url', 'notify_to', 'notify_date')

notification_system/main/views.py
# Django
from django.shortcuts import render
from django.contrib.auth import logout
from django.template import RequestContext, loader
from django.contrib.auth import authenticate, login
from django.http import HttpResponse, HttpResponseRedirect
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.db import OperationalError
from django.contrib import messages
from django.utils import timezone
from tasks import send_immediate_notification
from django import forms

# Django REST Framework
from rest_framework import viewsets, mixins

# Models
from main.models import *
from main.serializers import SnippetSerializer
from main.forms import UserForm, NotificationForm


@login_required(login_url='/main/login/')
def index(request):
    """
    Lists all the notifications a user has received.
    """
    if request.method == 'GET':
        print "index: " + str(request.user)
        notifications = Notification.objects.filter(
            notify_to__id=request.user.id,
            sent=True
        ).order_by('-notify_date')
        context = {'notifications': notifications}
        return render(request, 'main/index.html', context)


@login_required(login_url='/main/login/')
def runsql(request):
    """
    View to run sql query to fetch user ids from user table. Only the queries
    on table auth_user can be run correctly.
    :param request:
    :return:
    """
    if request.method == 'GET':
        query = request.GET['query']
        if 'select' not in query.lower() or 'auth_user' not in query.lower():
            return JsonResponse({
                "status": "error",
                "data": "Select queries only on the"
                        " table auth_user are allowed."
            })
        ret_data = []
        try:
            for u in User.objects.raw(query):
                ret_data.append({'id':u.id, 'username':u.username})
        except OperationalError:
            return JsonResponse({
                "status": "error",
                 "data": "Somethings wrong with the SQL. Please try again. "
                         "Note that user table is auth_user "
                         "and user id field is id."
            })
        if len(ret_data) > 0:
            return JsonResponse({
                "status": "success",
                "data": ret_data ,
                "msg": "SQL executed successfully. "
                       "Users to be notified are now added "
                       "to the notify_to form field"
            })
        else:
            return JsonResponse({
                "status": "error",
                "data": "No User present for the given selection criterion."
            })


@login_required(login_url='/main/login/')
def dashboard(request):
    """

    :param request:
    :return:
    """
    if request.method == 'POST':
        notif_form = NotificationForm(data=request.POST)
        if notif_form.is_valid():
            receivers = request.POST.getlist('notify_to')
            if len(receivers) > 0:
                notification = notif_form.save(commit=False)
                notification.notify_by = request.user
                notification.save()
                for receiver in receivers:
                    notification.notify_to.add(receiver)
                notification.save()
                messages.success(request, "Notification scheduled successfully!")

                # If the notification is created within 15 minutes from now, we
                # schedule it immediately with seconds countdown.
                delay_seconds = (notification.notify_date - timezone.now()).seconds
                if 0 < delay_seconds <= 900:
                    send_immediate_notification.apply_async(
                        (notification,),
                        countdown=delay_seconds
                    )
            notif_form = NotificationForm()
        else:
            print notif_form.errors
        print request.POST
    else:
        notif_form = NotificationForm()
    return render(
        request,
        'main/dashboard.html',
        {'notif_form': notif_form}
    )


######################
# Registration Views #
######################

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
            return HttpResponseRedirect('/main/login/')
        else:
            print user_form.errors
    else:
        user_form = UserForm()


    return render(request,
            'main/register.html',
            {'user_form': user_form, 'registered': registered} )


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/main/dashboard/')
            else:
                return HttpResponse("Your account is disabled.")
        else:
            print "Invalid login details: {0}, {1}".format(username, password)
            return HttpResponse("Invalid login details supplied.")

    else:
        return render(request, 'main/login.html', {})

def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/main/login/')


#########################
# Snippet RESTful Model #
#########################

class CRUDBaseView(mixins.ListModelMixin,
                  mixins.CreateModelMixin,
                  mixins.RetrieveModelMixin,
                  mixins.UpdateModelMixin,
                  mixins.DestroyModelMixin,
                  viewsets.GenericViewSet):
    pass

class SnippetView(CRUDBaseView):
    serializer_class = SnippetSerializer
    queryset = Snippet.objects.all()

notification_system/main/templates/main/api_examples.html
<html>
{% include 'main/base.html' %}
<body>


</body>
</html>

notification_system/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title> Notifications </title>
    <script src="/static/bower_components/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/static/bower_components/d3/d3.min.js"></script>
    
    <link rel="stylesheet" href="/static/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bower_components/bootstrap/dist/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/static/bower_components/bootstrap-social/bootstrap-social.css">
    <link rel="stylesheet" href="/static/bower_components/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/css/style.css">

  </head>
    
  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Notifications</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-left">
          {% if user.is_authenticated %}
          <li><a href="/main/dashboard">Create dashboard</a></li>
          {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if not user.is_authenticated %}
            <li class="active"><a href="/main/register">Register <span
                    class="sr-only">(current)</span></a></li>
            
            <li><a href="/main/login">Login</a></li>
          {% endif %}
            
        </ul>
        
        <ul  class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
    
            <li><a>Hello {{user}}</a></li>
            <li><a href="/main/logout/">Logout</a></li>
          {% endif %}
        </ul>
          
          
          </li>
         </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </body>
</html>

notification_system/main/templates/main/dashboard.html
<html>
{% include 'main/base.html' %}
<body>
<div class='container text-center'>
  <h2 class="form-heading">Create new notification</h2>
  <br>
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <div class="alert {{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
          </div>
        {% endfor %}
      </ul>
    {% endif %}
    <div class="form-group">
      <label for="query">Select user ids using SQL query:</label>
      <input type="text" class="form-control" id="query" value="select id from auth_user where id in (2,3);">
        <div id="sqlerror" class="alert alert-danger hidden">
        </div>
        <div id="sqlsuccess" class="alert alert-info hidden">
        </div>
        <a href="" class="btn btn-lg btn-primary" id="runsql">Run SQL</a>
    </div>
    <br>
  <form class="form-horizontal" id="user_form" method="post"
        action="/main/dashboard/" enctype="multipart/form-data">
    {% csrf_token %}
    {% load bootstrap %}
    <table>
        <tr>
          <td class="container text-center">
              <div class="form-group">
                  <label class="control-label col-sm-2 col-lg-2 " for="id_notify_to">Notify to</label>
                  <div class=" col-sm-10 col-lg-10 ">
                      <select multiple="multiple" class=" form-control" id="id_notify_to" name="notify_to">
                      </select>
                  </div>
              </div>
          </td>
        </tr>

        <tr>
          <td class="container text-center">{{ notif_form.header | bootstrap_horizontal}}</td>
        </tr>

        <tr>
          <td class="container text-center">{{ notif_form.content | bootstrap_horizontal}}</td>
        </tr>

        <tr>
          <td class="container text-center">{{ notif_form.image_url | bootstrap_horizontal}}</td>
        </tr>

        <tr>
          <td class="container text-center">{{ notif_form.notify_date | bootstrap_horizontal}}</td>
        </tr>

    </table>
    <button class="btn btn-lg btn-primary" type="submit">Create</button>
    <input type="hidden" name="submit" value="Register" />
  </form>
</div>
<script type="text/javascript" src="/static/js/main.js"></script>
</body>
</html>

notification_system/main/templates/main/index.html
<!DOCTYPE html>

<html>
    {% include 'main/base.html' %}

    <body>
    <div class="container">
    	{% if user.is_authenticated %}
            {% if notifications %}
                <div class="panel-group">
                {% for n in notifications %}
                    <div class="panel panel-primary">
                        <div class="panel-heading">{{ n.header }}</div>
                        <table class="table borderless">
                            <tr>
                                <td class="col-md-10">
                                    <p>Notification recieved on: {{ n.notify_date | date:"D d M Y H:i"}}</p>
                                </td>
                                <td class="col-md-2">
                                    <img src="{{ n.image_url }}" height="50px" width="50px">
                                </td>
                            </tr>
                            <tr>
                                <td class="col-md-12">
                                    {{ n.content }}
                                </td>
                            </tr>
                        </table>
                    </div>
                {% endfor %}
                </div>
            {% else %}
                No notifications recieved yet
            {% endif %}
        {% else %}
        	<h1> Please register/login to proceed! </h1>
        {% endif %}
    	<br>

	</div>
    </body>
</html>

notification_system/main/templates/main/login.html
<!DOCTYPE html>
<html>
    {% include 'main/base.html' %}
    <style>
      .form-signin {
        max-width: 550px;
        padding: 15px;
        margin: 0 auto;
      }
    </style>

    <body>
      <div class="container text-center">
        <form class="form-signin" id="login_form" method="post"
              action="/main/login/">
          {% csrf_token %}
          {% load bootstrap %}
          <h2 class="form-signin-heading">Login</h2>
          <br>
          <input type="text" name="username" class="form-control" placeholder="Username" value="" required autofocus>
          <br>
          <input type="password" name="password" class="form-control" placeholder="Password" value=""required>
          <br>
          <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
          <input type="hidden" name="submit" value="submit" />
        </form>
      </div>
    </body>
</html>

notification_system/main/templates/main/navbar.html
<body>
  <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Django Hackathon Starter</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          {% if not user.is_authenticated %}
            <li class="active"><a href="/main/register">Register <span
                    class="sr-only">(current)</span></a></li>
            
            <li><a href="/main/login">Login</a></li>
          {% endif %}
            
        </ul>
        
        <ul  class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
    
            <li><a>Hello {{user}}</a></li>
            <li><a href="/main/logout/">Logout</a></li>
          {% endif %}
        </ul>
          
          
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</body>

notification_system/main/templates/main/register.html
<!DOCTYPE html>
<html>
    {% include 'main/base.html' %}
    <link rel="stylesheet" href="/static/css/form.css">
    <body>
        {% if registered %}
          <strong>Thank you for registering!</strong>
          <a href="/main/login/">Return to the homepage.</a><br />
        
        {% else %}
          <div class='container text-center'>
              <h2 class="form-signin-heading">Sign Up</h2>
              <br>
              <form class="form-horizontal" id="user_form" method="post" action="/main/register/" enctype="multipart/form-data">
                {% csrf_token %}
                {% load bootstrap %} 

                <table>
                  <tr>
                     
                      <td class="container text-center">{{ user_form.username | bootstrap_horizontal}}</td>
                  </tr>

                  <tr>
                     
                      <td class="container text-center">{{ user_form.email | bootstrap_horizontal}}</td>
                  </tr>

                  <tr>
                     
                      <td class="container text-center">{{ user_form.password | bootstrap_horizontal}}</td>
                  </tr>
                </table>
                <button class="btn btn-lg btn-primary" type="submit">Register</button>
                <input type="hidden" name="submit" value="Register" />
              </form>
            </div>
          {% endif %}
    </body>
</html>